---
title: "Code Appendix"
format: docx
execute: 
  echo: true
  eval: false
  warning: false
---

## Set up

```{r}
rm(list = ls())
library(tidyverse)
library(hms)
library(here)
```


## Compiling and Formatting Data Frame

Here we will take the folder containing all the output files and load them into list:

```{r}
file_list <- list.files(path = here("output"), pattern = "[0-9].csv$",)

# read in all the files as dfs
df_list <- map(file_list, \(x) read_csv(here("output", x)))

# process each df to then bind_rows
cleaned_list <- map(df_list, \(x) x |> relocate(file) |>
  pivot_longer(4:ncol(x), names_to = "species", values_to = "probability") |>
  filter(!is.na(probability)))

# add a column with the AM name
for (i in 1:length(cleaned_list)){
  cleaned_list[[i]] <- cleaned_list[[i]] |> 
    mutate(id = str_sub(file_list[[i]], start = 8, end = -5)) # AM names of variable length
}

# compile into single df
temp_df <- bind_rows(cleaned_list)
```


### Create date and time variables

```{r}
main_df <- temp_df |> mutate(date = str_sub(file, start = 1, end = 8),
          hour = str_sub(file, 10, 11),
          minute = str_sub(file, 12, 13),
          second = start) |>
  unite("date_time", c("date", "hour", "minute", "second"), sep = ":") |>
  mutate(date_time = ymd_hms(date_time),
          time = as_hms(date_time))
```


## Write csv

```{r}
write_csv(main_df, here("data/birdnet_results.csv"))
```


## Merge with deployment data

```{r}
deploy <- read_csv(here("data/Updated_baggie_case_deployments.csv"))
```

```{r}
merged <- left_join(deploy, main_df, join_by("deployment_num" == "id"))
glimpse(merged)
```

#### Write merged csv

```{r}
write_csv(merged, here("data/merged_deployment_birdnet.csv"))
```


# Python

```{python python.reticulate = FALSE}
from pathlib import Path

from birdnet import SpeciesPredictions, predict_species_within_audio_file
import time

import pandas as pd

folder_path = Path("A017_SD017")
audio_files = list(folder_path.rglob("*.WAV"))
audio_files


species_list_path = Path("species_list.txt")



with species_list_path.open() as f:
   species_list = {line.strip() for line in f if line.strip()}  # curly braces = set



all_dfs = [] ## storage

for audio_path in audio_files:
    print(f"Processing {audio_path.name}...")

    start = time.perf_counter()

    # Run the prediction
    predictions = SpeciesPredictions(
        predict_species_within_audio_file(
            audio_path,
            min_confidence=0.4,
            chunk_overlap_s=0.0,
            species_filter= species_list

        )
    )

    # Convert predictions to a DataFrame
    df = pd.DataFrame([
        {'start': start_t, 'end': end_t, **species_probs}
        for (start_t, end_t), species_probs in predictions.items()
    ])

    # Add audio file identifier
    df['file'] = audio_path.name 

    end = time.perf_counter()
    print(f"Finished {audio_path.name} in {end - start:.2f} seconds")

    all_dfs.append(df)

all_dfs
combined_df = pd.concat(all_dfs, ignore_index=True)
combined_df.to_csv("output_A017_SD017.csv", index=False)
```

```{r ref.label=knitr::all_labels()}
#| echo: true
#| eval: false
```
